### ISSUE TITLE
Pre-build stack in constructor for performance enhancement

### ISSUE THREAD

**Issue by mmcc007** [mmcc007/modal_progress_hud#16]
You are welcome, thank you for implementing such good idea of modal hud!

Btw, I think that solution can be optimized even further because we can create a list of widgets for a stack right in the constructor, remove the most of logic and construction from the build function and only return there "child" or "stack" depending on async flag.

But the most important was done already: do not complicate the widgets hierarchy in the most common case when hud is off.

_Originally posted by @arsenioo in https://github.com/mmcc007/modal_progress_hud/pull/14#issuecomment-474314257_

**Comment by mmcc007** [comment]
@arsenioo Thanks for the kind words.

As you suggest, all widgets can be built once in the constructor and re-used on demand in the build method. 

Means a slower startup of ModalProgressHUD. However, if we can assume the build method is called frequently in the app, suggestion should result in improved performance.

What do you think... is it worth it?

**Comment by arsenioo** [comment]
You know, as I told before the most important improvement was to simplify the hierarchy of the "default", non-hud widget tree. Now we have 2 options, no... actually 3 :)
1) Leave all as is.
2) Create stack widget in the constructor. This means slower object init and more resources consumption even if hud mode never used.
3) Implement deferred stack widget: create it once, inside the build method but only on demand at the first hud usage only, then use stored field. Perhaps this is would be the most universal and effective implementation, do you agree?

But anyway it is rather some perfectionism than the major improvement, just to polish the idea :)

If you wish, I can do this a bit later just as an exercise

**Comment by mmcc007** [comment]
A classic engineering tradeoff :)
Unlike your great PR #14, not a clear performance win in any option!

What we have now seems to work great (with no obvious performance issue). So for now, if ok, I will leave it up to you how you want to proceed.

I suppose some performance testing could allow comparison of different approaches. But, as you say, it is more of fun experimentation at this point.
