### ISSUE TITLE
Size missing exception

### ISSUE THREAD

**Issue by jasonlaw** [mmcc007/modal_progress_hud#18]
Seeing this when inAsyncCall = true.

![image](https://user-images.githubusercontent.com/107820/55691618-7ad08180-59d2-11e9-836d-48f4b4810faf.png)

**Comment by mmcc007** [comment]
Hard to tell without looking at code. 

Could be a constraint limit being exceeded in the descendants of child as a result of widgets added around child when inAsyncCall=true

You could try relaxing the constraints on the descendants of child

**Comment by jasonlaw** [comment]
I am trying to use this on the teddy example from flare package (https://github.com/2d-inc/Flare-Flutter).
So may be this is just not an valid issue at all. You may close it.
Thanks for the fast response anyway, really appreciate!

**Comment by mmcc007** [comment]
Sure.. no prob.

Feel free to re-open if it looks like a problem with this widget

**Comment by kleyos** [comment]
Hey. the same problem happened in my code when I try to use hud inside of SliverBoxAdapter. How I can workaround this?

**Comment by kleyos** [comment]
> Hey. the same problem happened in my code when I try to use hud inside of SliverBoxAdapter. How I can workaround this?

Resolved. Just wrapped CustomScrollView with hud. not vise-versa
