### ISSUE TITLE
Minimum duration

### ISSUE THREAD

**Issue by FilipeOS** [mmcc007/modal_progress_hud#19]
Hi there,

How can we add a minimum duration?
For example the spinner will always take 2 seconds at least?

**Comment by mmcc007** [comment]
Not sure why you would want to do this. 

If you are expecting a 2 second delay (which is probably an unpleasant experience for the user), and the delay is beyond your control, then it seems the user just has to deal with it, if/when it comes-up. You might want to consider how you can reduce the delay.

Can you provide a use case where you need to show a minimum delay?

**Comment by FilipeOS** [comment]
For example you are saving user settings and you want that user knows it's saving. Showing a loading for at least 1 or 2 seconds it's a must. Or user don't know it was saved sometimes

**Comment by mmcc007** [comment]
One simple way to add an artificial delay is to perhaps precede the actual delay with another call to wait for a future of a set duration to return before continuing. As in:
https://github.com/mmcc007/modal_progress_hud/blob/8ab3fa868611c934a6688be153cd08b3f521def8/example/lib/main.dart#L90
