### ISSUE TITLE
dart sdk 2.1 not compatible  ? 

### ISSUE THREAD

**Issue by nitneuq33000** [mmcc007/modal_progress_hud#2]
hello, I upgrade dart sdk to 2.1 but I have error with flutter packages get. modal progress hud not compatible .. .

**Comment by mmcc007** [comment]
Sorry about that... I hope I can help.

I ran example test with
```
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.12.6 16G1036, locale en-US)
    • Flutter version 0.9.4 at /Users/jenkins/Library/flutter
    • Framework revision f37c235c32 (3 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044
```
It should be compatible up to version 3.0.0. Try setting
```yaml
  modal_progress_hud: ^0.1.1
```
to
```yaml
  modal_progress_hud: any
```
to see if there is still a version conflict in your app.

Can you run the example?

If still a problem can you send me the output of `flutter doctor -v` or better still post an example that reproduces the problem.

**Comment by nitneuq33000** [comment]
hello I all reinstall, flutter + git + android studio, I just add modal
progress hud to pubspec.yaml and copy past the exemple and I have this
error

The current Dart SDK version is 2.1.0-dev.5.0.flutter-a2eb050044.

Because test1 depends on modal_progress_hud ^0.0.2 which requires SDK
version >=1.19.0 <2.0.0, version solving failed.

pub get failed (1)


here is my pubspec.yalm


environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  modal_progress_hud: "^0.0.5"
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

and the flutter doctor


utilisateur@DESKTOP-638FO60 MINGW64 ~/AndroidStudioProjects/nirbi (master)
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.9.4, on Microsoft Windows [version
10.0.17134.345], locale fr-FR)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[!] VS Code, 64-bit edition (version 1.21.1)
[√] Connected devices (1 available)

! Doctor found issues in 1 category.

utilisateur@DESKTOP-638FO60 MINGW64 ~/AndroidStudioProjects/nirbi (master)
$ ^C

utilisateur@DESKTOP-638FO60 MINGW64 ~/AndroidStudioProjects/nirbi (master)
$

thank you


Le sam. 20 oct. 2018 à 11:18, Maurice McCabe <notifications@github.com> a
écrit :

**Comment by nitneuq33000** [comment]
Sorry problem solved. I didn't use the lasted version ... T_T

**Comment by mmcc007** [comment]
Glad u got it working👍
