### ISSUE TITLE
HUD is not appearing

### ISSUE THREAD

**Issue by x8Haider** [mmcc007/modal_progress_hud#20]
Hi,

I got this error from logs:

I/flutter (29162): Another exception was thrown: BoxConstraints forces an infinite height.
I/flutter (29162): Another exception was thrown: RenderBox was not laid out: RenderConstrainedBox#5e18e relayoutBoundary=up15 NEEDS-PAINT
I/flutter (29162): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#32bdb relayoutBoundary=up14 NEEDS-PAINT
I/flutter (29162): Another exception was thrown: RenderBox was not laid out: RenderPointerListener#980e2 relayoutBoundary=up13 NEEDS-PAINT
I/flutter (29162): Another exception was thrown: RenderBox was not laid out: RenderSemanticsGestureHandler#24ed8 relayoutBoundary=up12 NEEDS-PAINT
I/flutter (29162): Another exception was thrown: RenderBox was not laid out: RenderExcludeSemantics#76cbb relayoutBoundary=up11 NEEDS-PAINT
I/flutter (29162): Another exception was thrown: RenderBox was not laid out: RenderBlockSemantics#56409 relayoutBoundary=up10 NEEDS-PAINT
I/flutter (29162): Another exception was thrown: RenderBox was not laid out: RenderOpacity#6bd88 relayoutBoundary=up9 NEEDS-PAINT

**Comment by mmcc007** [comment]
This may be a problem with layout of your screen. If `!inAsyncCall`, modal_progress_hud does nothing:
https://github.com/mmcc007/modal_progress_hud/blob/8ab3fa868611c934a6688be153cd08b3f521def8/lib/modal_progress_hud.dart#L49
To verify this, you could try removing modal_progress_hud and confirm your screen layout is working.
