### ISSUE TITLE
It doesn't work,if i call othen method Under the showState Until the method is executed

### ISSUE THREAD

**Issue by jjjachyty** [mmcc007/modal_progress_hud#22]
and i use
```
new Future.delayed(new Duration(seconds: 1), () {
     //call othen methond
      });
```
the circle Stop turning, how can i use this？
@mmcc007

**Comment by mmcc007** [comment]
Run the example app to see a modal_progress_hud in action.
```
git clone https://github.com/mmcc007/modal_progress_hud.git
cd modal_progress_hud/example
flutter run
```
Review the example code and see if this helps.
https://github.com/mmcc007/modal_progress_hud/blob/master/example/lib/main.dart
