### ISSUE TITLE
Expose stack alignment

### ISSUE THREAD

**Issue by Prn-Ice** [mmcc007/modal_progress_hud#33]
Im using your plugin with a bottomsheet and it aligned the bottomsheet to the top of the screen on load.

Editing the source fixed this:
```dart
return new Stack(
      alignment: Alignment.bottomCenter // Added this,
      children: widgetList,
    );
```

**Comment by JohnOnLee** [comment]
have you tried to use offset?
https://github.com/mmcc007/modal_progress_hud/blob/dea451b13aba9cbb08d9086bd226dd50ef3355bd/lib/modal_progress_hud.dart#L52-L60

**Comment by Prn-Ice** [comment]
No, I'll try that later
